/**
 * Demo Gateway
 *
 * Demo Gateway.
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param propertyKeys 
 */

data class ExampleResponse (

    @SerializedName("keys")
    val propertyKeys: kotlin.collections.List<kotlin.String>

)

